lib/shovik_com_web/router.ex
defmodule ShovikComWeb.Router do
  use ShovikComWeb, :router
  use Honeybadger.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ShovikComWeb.Auth
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  scope "/", ShovikComWeb do
    pipe_through :browser

    get "/", HomeController, :index

    resources "/blog", BlogController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", ShovikComWeb do
  #   pipe_through :api
  # end
end

lib/shovik_com_web/views/layout_view.ex
defmodule ShovikComWeb.LayoutView do
  use ShovikComWeb, :view

  def render_menu_item(conn, path, title, options \\ []) do
    li_class = if conn.assigns[:menu] == title, do: "is-active", else: ""

    content_tag :li, class: li_class do
      link title, Keyword.merge(options, to: path)
    end
  end
end

lib/shovik_com_web/templates/layout/_flashes.html.eex
<% info = get_flash(@conn, :info) %>
<% error = get_flash(@conn, :error) %>

<%= if info do %>
  <div class="notification is-primary">
    <button class="delete"></button>
    <%= info %>
  </div>
<% end %>

<%= if error do %>
  <div class="notification is-danger">
    <button class="delete"></button>
    <%= error %>
  </div>
<% end %>

lib/shovik_com_web/templates/layout/_foot.html.eex
<footer class="footer content has-background-dark has-text-light">
  <div class="container has-text-centered">
    <div class="columns">
      <div class="column is-one-third has-text-left">
        <ul class="list-no-bullets">
          <li><i class="fab fa-twitter"></i>&nbsp;<a href="https://twitter.com/ashovik" title="Alex Kovshovik's Twitter profile">@ashovik</a></li>
          <li><i class="fab fa-stack-overflow"></i>&nbsp;<a href="http://stackoverflow.com/users/115680/alex-kovshovik" title="Alex Kovshovik's StackOverflow profile">StackOverflow</a></li>
          <li><i class="fab fa-linkedin-in"></i>&nbsp;<a href="https://www.linkedin.com/in/alex-kovshovik-4532588" title="Alex Kovshovik's LinkedIn profile">LinkedIn</a></li>
          <li><i class="fab fa-gitlab"></i>&nbsp;<a href="https://gitlab.com/alex-kovshovik" title="Alex Kovshovik's GitLab profile">GitLab</a></li>
          <li><i class="fab fa-github"></i>&nbsp;<a href="https://github.com/alex-kovshovik" title="Alex Kovshovik's GitHub profile">GitHub</a></li>
        </ul>
      </div>

      <div class="column is-two-thirds">
        <p>
          <br/>
          This site is powered by <a href="http://elixir-lang.org">Elixir</a> and <a href="http://phoenixframework.org">Phoenix Framework</a>
          mostly because I like to play with things, however <a href="http://elixir-lang.org">Elixir</a> is such a pleasure to work with, I hope
          to use it for serious projects.
        </p>

        <p>
          We have access to the <a href="https://cleverlabs.io/">team of professional developers</a>
          in <a href="https://www.google.com/maps/place/Belarus/@53.6331332,23.4939995,6z/data=!3m1!4b1!4m5!3m4!1s0x46da2584e2ad4881:0xa1d181ec8c10!8m2!3d53.709807!4d27.953389">Belarus</a>
          who can help you create solid technology solutions.
        </p>

        <p>
          What's new: <%= link System.get_env("COMMIT_HASH"), to: "https://gitlab.com/shovik-group/shovik-com/commit/#{System.get_env("COMMIT_HASH_LONG")}" %>
        </p>
      </div>
    </div>

    <p>
      Copyright &copy; <%= Timex.today.year %> Alex Kovshovik
    </p>
  </div>
</footer>

lib/shovik_com_web/templates/layout/_head.html.eex
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="description" content="Beautiful software for humans, consulting, problem solving.">
  <meta name="author" content="Alex Kovshovik">
  <title>Shovik Software</title>

  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">

  <link rel="apple-touch-icon" sizes="57x57" href="<%= Routes.static_path(@conn, "/images/favicon/apple-icon-57x57.png") %>">
  <link rel="apple-touch-icon" sizes="60x60" href="<%= Routes.static_path(@conn, "/images/favicon/apple-icon-60x60.png") %>">
  <link rel="apple-touch-icon" sizes="72x72" href="<%= Routes.static_path(@conn, "/images/favicon/apple-icon-72x72.png") %>">
  <link rel="apple-touch-icon" sizes="76x76" href="<%= Routes.static_path(@conn, "/images/favicon/apple-icon-76x76.png") %>">
  <link rel="apple-touch-icon" sizes="114x114" href="<%= Routes.static_path(@conn, "/images/favicon/apple-icon-114x114.png") %>">
  <link rel="apple-touch-icon" sizes="120x120" href="<%= Routes.static_path(@conn, "/images/favicon/apple-icon-120x120.png") %>">
  <link rel="apple-touch-icon" sizes="144x144" href="<%= Routes.static_path(@conn, "/images/favicon/apple-icon-144x144.png") %>">
  <link rel="apple-touch-icon" sizes="152x152" href="<%= Routes.static_path(@conn, "/images/favicon/apple-icon-152x152.png") %>">
  <link rel="apple-touch-icon" sizes="180x180" href="<%= Routes.static_path(@conn, "/images/favicon/apple-icon-180x180.png") %>">
  <link rel="icon" type="image/png" sizes="192x192" href="<%= Routes.static_path(@conn, "/images/favicon/android-icon-192x192.png") %>">
  <link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/images/favicon/favicon-32x32.png") %>">
  <link rel="icon" type="image/png" sizes="96x96" href="<%= Routes.static_path(@conn, "/images/favicon/favicon-96x96.png") %>">
  <link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/images/favicon/favicon-16x16.png") %>">
</head>

lib/shovik_com_web/templates/layout/_menu.html.eex
<nav class="navbar">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <img src="/images/favicon/favicon-96x96.png" alt="Logo">
        &nbsp;Shovik Software
      </a>
      <span class="navbar-burger burger" data-target="navbarMenu">
        <span></span>
        <span></span>
        <span></span>
      </span>
    </div>
    <div id="navbarMenu" class="navbar-menu">
      <div class="navbar-end">
        <div class="tabs is-right">
          <ul>
            <%= render_menu_item(@conn, "/", "Home") %>
            <%= render_menu_item(@conn, Routes.blog_path(@conn, :index), "Blog") %>
            <%= if @current_user do %>
              <%= render_menu_item(@conn, Routes.session_path(@conn, :delete, @current_user), "Logout", method: :delete) %>
            <% else %>
              <%= render_menu_item(@conn, Routes.session_path(@conn, :new), "Login") %>
            <% end %>
            <%# <%= render_menu_item(@conn, "/", "Portfolio") %>
            <%# <%= render_menu_item(@conn, "/", "Contact") %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

lib/shovik_com_web/templates/layout/_scripts.html.eex
<script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.8/styles/atom-one-light.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.8/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-44951720-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-44951720-3');
</script>

lib/shovik_com_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <%= render "_head.html", conn: @conn %>
  <body>
    <%= render "_flashes.html", conn: @conn %>

    <section class="hero is-default is-bold">
      <div class="hero-head">
        <%= render "_menu.html", conn: @conn, current_user: @conn.assigns.current_user %>
      </div>
    </section>

    <div class="container">
      <%= render @view_module, @view_template, assigns %>
    </div>
    
    <%= render "_foot.html", conn: @conn %>
    <%= render "_scripts.html", conn: @conn %>
  </body>
</html>

lib/shovik_com_web/templates/layout/home.html.eex
<!DOCTYPE html>
<html lang="en">
  <%= render "_head.html", conn: @conn %>
  <body>
    <%= render "_flashes.html", conn: @conn %>

    <section class="hero is-fullheight is-default is-bold">
      <%= render @view_module, @view_template, assigns %>
      <%= render "_foot.html", conn: @conn %>
    </section>

    <%= render "_scripts.html", conn: @conn %>
  </body>
</html>